#!/bin/sh
 
usage() {
echo "$0 uploads from files or stdin to http://sprunge.us.  Fit it into a pipeline like any other unix tool, you're not an idiot."
}
 
if [ -t 0 ]; then
  #Running interactively, checking for arguments... 
  if [ "$*" ]; then
    #echo Arguments present... 
    if [ -f "$*" ]; then
      #Uploading the contents of "$*"... 
      cat "$*"
    else
      #Uploading the text "$*"... 
      echo "$*"
    fi | curl -F 'sprunge=<-' http://sprunge.us
  else
    #No arguments found, printing usage and exiting. 
    usage
  fi
else
  #Using input from a pipe or STDIN redirection... 
  while read -r line ; do
    echo $line
  done | curl -F 'sprunge=<-' http://sprunge.us
fi

